CREATE SCHEMA IF NOT EXISTS mjga;

CREATE TABLE mjga."user"
(
    "id"          BIGINT    NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "username"    VARCHAR   NOT NULL UNIQUE,
    "create_time" TIMESTAMP NOT NULL DEFAULT now(),
    "password"    VARCHAR   NOT NULL,
    "enable"      BOOLEAN   NOT NULL DEFAULT true,
    PRIMARY KEY ("id")
);

CREATE TABLE mjga."permission"
(
    "id"   BIGINT  NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "code" VARCHAR NOT NULL,
    "name" VARCHAR NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE mjga."role"
(
    "id"   BIGINT  NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "code" VARCHAR NOT NULL,
    "name" VARCHAR NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE mjga."role_permission_map"
(
    "id"            BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "role_id"       BIGINT NOT NULL,
    "permission_id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE mjga."user_role_map"
(
    "id"      BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE mjga."user_role_map"
    ADD FOREIGN KEY ("user_id") REFERENCES mjga."user" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE mjga."user_role_map"
    ADD FOREIGN KEY ("role_id") REFERENCES mjga."role" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE mjga."role_permission_map"
    ADD FOREIGN KEY ("role_id") REFERENCES mjga."role" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE mjga."role_permission_map"
    ADD FOREIGN KEY ("permission_id") REFERENCES mjga."permission" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
